### PR TITLE
include pkg/{node,web}/* in tarball

### PR DESCRIPTION
**Pull request by jbr**

### CODE REVIEW

**Comment by jbr** [comment]
I'd merge this directly if I could; I just forgot it in previous PR

**Review by divergentdave — APPROVED** [review]
LGTM. I'd like to request one more fixup: `npm i --save-dev run-s`, as I didn't have that installed, and ran into it when building locally.

**Comment by jbr** [comment]
I'm confused about what's happening here. You did `npm install` and still can't `npm exec -- run-s --help`? `npm-run-all` is a dev dependency already.

**Comment by divergentdave** [comment]
Oh nevermind, I hadn't run `npm install` first, but that fixes it. Thanks!

**Pull request merged**
